# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Pyhat
                                 A QGIS plugin
 Uses PyHAT algorithms to allow application of these algorithms through QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-11
        copyright            : (C) 2018 by USGS Astrogeology
        email                : tthatcher@usgs.gov
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Pyhat class from file Pyhat.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pyhat import Pyhat
    return Pyhat(iface)
